[package]
name = "noaa-apt"
version = "0.9.6"
authors = ["Martin Bernardi <martinber.710@gmail.com>"]

[dependencies]
hound = "*"
rustfft = "*"
approx = "*"
png = "*"
log = "*"
simple_logger = "*"
argparse = "*"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_10"]

[dependencies.gdk]
version = "0.9.0"

[dependencies.gio]
version = "0.5.0"
