[package]
name = "noaa-apt"
version = "1.0.1-dev"
authors = ["Martin Bernardi <martinber.710@gmail.com>"]
build = "src/build.rs"

[profile.dev]
# So the dev builds run faster, otherwise they are extremely slow
opt-level = 3

[profile.release]
# I don't like silent overflows
overflow-checks = true

[features]
default = ["gui"]
gui = ["gtk", "gdk", "gio", "glib"]
# static_ssl = ["openssl/vendored"]

[dependencies]
num = "*"
hound = "*"
rustfft = "*"
approx = "*"
png = "*"
log = "*"
simple_logger = "*"
argparse = "*"
reqwest = "*"
directories = "*"
toml = "*"
serde = { version = "*", features = ["derive"] }
# openssl = "0.10"

gtk = { git = "https://github.com/EPashkin/gtk.git", branch = "fontchooserlevel_version", optional = true, features = ["v3_16"] }
gdk = { git = "https://github.com/gtk-rs/gdk.git", optional = true }
gio = { git = "https://github.com/gtk-rs/gio.git", optional = true }
glib = { git = "https://github.com/gtk-rs/glib.git", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["shellapi"] }
