[package]
name = "noaa-apt"
version = "0.9.6"
authors = ["Martin Bernardi <martinber.710@gmail.com>"]

[features]
default = ["gui"]
gui = ["gtk", "gdk", "gio"]

[dependencies]
num = "*"
hound = "*"
rustfft = "*"
approx = "*"
png = "*"
log = "*"
simple_logger = "*"
argparse = "*"
reqwest = "*"

gtk = { version = "0.5.0", optional = true, features = ["v3_10"] }
gdk = { version = "0.9.0", optional = true }
gio = { version = "0.5.0", optional = true }
