[package]
name = "noaa-apt"
version = "1.0.0"
authors = ["Martin Bernardi <martinber.710@gmail.com>"]
build = "src/build.rs"

[profile.dev]
# So the dev builds run faster, otherwise they are extremely slow
opt-level = 3

[profile.release]
# I don't like silent overflows
overflow-checks = true

[features]
default = ["gui"]
gui = ["gtk", "gdk", "gio", "glib"]

[dependencies]
num = "*"
hound = "*"
rustfft = "*"
approx = "*"
png = "*"
log = "*"
simple_logger = "*"
argparse = "*"
reqwest = "*"
directories = "*"
toml = "*"
serde = { version = "*", features = ["derive"] }

gtk = { version = "0.6.0", optional = true, features = ["v3_16"] }
gdk = { version = "0.10.0", optional = true }
gio = { version = "0.6.0", optional = true }
glib = { version = "0.7.0", optional = true }
