[package]
name = "noaa-apt"
version = "0.9.5"
authors = ["Martin Bernardi <martinber.710@gmail.com>"]

[dependencies]
hound = "*"
png = "*"
log = "*"
simple_logger = "*"
argparse = "*"

[dependencies.gtk]
version = "0.4.1"
features = ["v3_10"]

[dependencies.gdk]
version = "0.8.0"

[dependencies.gio]
version = "0.4.1"

[dev-dependencies]
GSL = "*"

[dev-features]
GSLv2 = ["GSL/v2"]
